/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculadora;

import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        btoSoma = new javax.swing.JButton();
        btoDivisao = new javax.swing.JButton();
        btoMultiplicacao = new javax.swing.JButton();
        txtbResultado = new javax.swing.JTextField();
        btoResultado = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btoSubtracao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("1º Numero");

        jLabel2.setText("2º Numero");

        btoSoma.setText("+");
        btoSoma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btoSomaMouseClicked(evt);
            }
        });
        btoSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoSomaActionPerformed(evt);
            }
        });

        btoDivisao.setText("/");
        btoDivisao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btoDivisaoMouseClicked(evt);
            }
        });
        btoDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoDivisaoActionPerformed(evt);
            }
        });

        btoMultiplicacao.setText("X");
        btoMultiplicacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btoMultiplicacaoMouseClicked(evt);
            }
        });
        btoMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoMultiplicacaoActionPerformed(evt);
            }
        });

        txtbResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbResultadoActionPerformed(evt);
            }
        });

        btoResultado.setText("Resultado");

        jLabel3.setText("Calculadora");

        btoSubtracao.setText("-");
        btoSubtracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btoSubtracaoMouseClicked(evt);
            }
        });
        btoSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoSubtracaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txt2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtbResultado)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btoSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btoSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btoResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btoDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btoMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btoSoma)
                    .addComponent(btoDivisao)
                    .addComponent(btoSubtracao)
                    .addComponent(btoMultiplicacao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btoResultado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btoDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoDivisaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btoDivisaoActionPerformed

    private void txtbResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbResultadoActionPerformed

    private void btoSomaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btoSomaMouseClicked
        // TODO add your handling code here:
        
        
        //double soma = numero1 + numero2;
        
        while(txt1.getText().isBlank()){
            txt1.setText(JOptionPane.showInputDialog("Digite um valor numerica"));
        }
        while (txt2.getText().isBlank()) {
           txt2.setText(JOptionPane.showInputDialog("Digite um valor numerica"));
            
        }
            
        double numero1 = Double.parseDouble(txt1.getText());
        double numero2 = Double.parseDouble(txt2.getText());
        txtbResultado.setText(Double.toString(Calcular.somar(numero1, numero2)));
        
        //System.out.println("Soma = " + soma);
        
    }//GEN-LAST:event_btoSomaMouseClicked

    private void btoSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoSomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btoSomaActionPerformed

    private void btoSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoSubtracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btoSubtracaoActionPerformed

    private void btoSubtracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btoSubtracaoMouseClicked
        // TODO add your handling code here:
        //double soma = numero1 + numero2;
        
        while(txt1.getText().isBlank()){
            txt1.setText(JOptionPane.showInputDialog("Digite um valor numerica"));
        }
        while (txt2.getText().isBlank()) {
           txt2.setText(JOptionPane.showInputDialog("Digite um valor numerica"));
            
        }
            
        double numero1 = Double.parseDouble(txt1.getText());
        double numero2 = Double.parseDouble(txt2.getText());
        txtbResultado.setText(Double.toString(Calcular.subtrair(numero1, numero2)));
    }//GEN-LAST:event_btoSubtracaoMouseClicked

    private void btoDivisaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btoDivisaoMouseClicked
        // TODO add your handling code here:
        
        
        while(txt1.getText().isBlank()){
            txt1.setText(JOptionPane.showInputDialog("Digite um valor numerica"));
        }
        while (txt2.getText().isBlank()) {
           txt2.setText(JOptionPane.showInputDialog("Digite um valor numerica"));
            
        }
        double numero1 = Double.parseDouble(txt1.getText());
        double numero2 = Double.parseDouble(txt2.getText());
        if(numero2 == 0){
            txtbResultado.setText("Nao e possivel dividir por ZERO!");
        }
        
        txtbResultado.setText(Double.toString(Calcular.dividir(numero1, numero2)));
    }//GEN-LAST:event_btoDivisaoMouseClicked

    private void btoMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoMultiplicacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btoMultiplicacaoActionPerformed

    private void btoMultiplicacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btoMultiplicacaoMouseClicked
        // TODO add your handling code here:
        while(txt1.getText().isBlank()){
            txt1.setText(JOptionPane.showInputDialog("Digite um valor numerica"));
        }
        while (txt2.getText().isBlank()) {
           txt2.setText(JOptionPane.showInputDialog("Digite um valor numerica"));
            
        }
            
        double numero1 = Double.parseDouble(txt1.getText());
        double numero2 = Double.parseDouble(txt2.getText());
        txtbResultado.setText(Double.toString(Calcular.multiplicar(numero1, numero2)));
    }//GEN-LAST:event_btoMultiplicacaoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btoDivisao;
    private javax.swing.JButton btoMultiplicacao;
    private javax.swing.JButton btoResultado;
    private javax.swing.JButton btoSoma;
    private javax.swing.JButton btoSubtracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txtbResultado;
    // End of variables declaration//GEN-END:variables
}
